Repository metal3-io/ironic-image, pull requests merged in 2019-10, with the labels that each got.

#98 dnsmasq: dhcp options doc fix
  dnsmasq.conf
Labels: size/XS

#99 Ensure genisoimage is installed so Ironic can build configdrive
  Dockerfile
Labels: size/XS

#93 Move to Train branch
  Dockerfile
Labels: CI, approved, lgtm, size/XS

#101 Re-adding Train features
  Dockerfile
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
  runironic-exporter.sh
Labels: CI, approved, size/M

#106 Disabling mdns for ipv6 testing
  inspector.ipxe
  ironic.conf
Labels: approved, lgtm, size/XS

#109 Removing forgotten mdns conf param
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#103 Enable RAID interfaces for Ironic container
  ironic.conf
Labels: approved, lgtm, size/XS

#110 Use generic python-chardet
  Dockerfile
Labels: approved, lgtm, size/XS

#111 Do not install python-chardet explicitly
  Dockerfile
Labels: approved, lgtm, size/XS
