Repository metal3-io/ironic-image, pull requests merged in 2019-11, with the labels that each got.

#105 Enable fast_track provisioning for nodes
  configure-ironic.sh
Labels: CI, approved, lgtm, size/XS

#107 Changes needed for IPv6
  Dockerfile
  configure-ironic.sh
  dnsmasq.conf.ipv4
  dnsmasq.conf.ipv6
  ironic-common.sh
  rundnsmasq.sh
  runhealthcheck.sh
  runhttpd.sh
Labels: CI, approved, lgtm, size/L

#104 Remove iptables filters from ironic containers
  Dockerfile
  rundnsmasq.sh
  runhttpd.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
Labels: CI, approved, lgtm, size/M

#97 Stop logging to file
  rundnsmasq.sh
  runhttpd.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
  runmariadb.sh
Labels: CI, approved, lgtm, size/M
