Repository metal3-io/ironic-image, pull requests merged in 2020-08, with the labels that each got.

#167 Make ironic timeouts customizable
  README.md
Labels: approved, lgtm, size/XS

#186 Configure ironic-conductor to auth to ironic-inspector
  configure-ironic.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
Labels: approved, lgtm, size/S

#184 Remove all unused modules
  Dockerfile
  httpd-modules.conf
  httpd.conf
Labels: approved, lgtm, size/S

#162 enable idrac-wsman BIOS interface
  ironic.conf
Labels: approved, lgtm, ok-to-test, size/XS, ¯\_(ツ)_/¯

#189 Disable bios interfaces idrac-wsman
  ironic.conf
Labels: approved, lgtm, size/XS

#190 Use collector name in ironic.conf expected by IPA
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#187 feat: enable ibmc raid interface
  ironic.conf
Labels: approved, lgtm, size/XS
