Repository metal3-io/ironic-image, pull requests merged in 2020-07, with the labels that each got.

#163 Update inspection configuration to enable fast-track
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
Labels: approved, lgtm, size/S

#173 Set power_off = !fast_track in [inspector]
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
  runhttpd.sh
Labels: approved, lgtm, size/M

#172 Configure ironic to use Ipmitool retries
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
Labels: approved, lgtm, size/S

#165 Add ability to set arbitrary ironic configs
  README.md
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#168 Add http_basic auth support
  configure-ironic.sh
Labels: approved, lgtm, size/S

#179 Set the hash ring algorithm to SHA256
  ironic.conf
Labels: approved, lgtm, size/XS

#180 Limit unauthenticated json-rpc to localhost interface
  configure-ironic.sh
  ironic.conf
  runironic-conductor.sh
  runironic.sh
Labels: approved, lgtm, size/S

#185 Fix typo in basic auth config
  configure-ironic.sh
Labels: approved, lgtm, size/XS
