Repository metal3-io/ironic-image, pull requests merged in 2020-11, with the labels that each got.

#212 Secure boot compatible ESP image
  Dockerfile
  ironic.conf.j2
Labels: approved, lgtm, size/S

#208 Merge RUN commands to reduce layers number
  Dockerfile
Labels: approved, lgtm, size/XS

#215 Correct the destination grub path when building an ESP image
  Dockerfile
Labels: approved, lgtm, size/XS

#214 Limit the default number of API workers to 4
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#206 Make Ironic connect to Mariadb using TLS
  configure-ironic.sh
  ironic.conf.j2
  runmariadb.sh
Labels: approved, lgtm, size/M

#218 Add redfish as an enabled BIOS interface
  ironic.conf.j2
Labels: approved, lgtm, size/XS

#217 Add new entry point script to dump ramdisk host provisioning logs
  Dockerfile
  README.md
  runlogwatch.sh
Labels: approved, lgtm, size/S

#221 Add runlogwatch.sh +x permission
  runlogwatch.sh
Labels: approved, lgtm, size/XS

#213 Add zaneb as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#225 Move upgrade and install logic to a script
  Dockerfile
  prepare-image.sh
Labels: approved, lgtm, size/S

#229 Add options to disable TLS validations
  configure-ironic.sh
  ironic.conf.j2
Labels: approved, lgtm, size/XS
