Repository metal3-io/ironic-image, pull requests merged in 2020-01, with the labels that each got.

#120 ironic image virtual media fixups
  Dockerfile
  configure-ironic.sh
  ironic.conf
  runironic-conductor.sh
Labels: approved, lgtm, size/S

#118 Adds idrac-redfish interface variations as options
  ironic.conf
Labels: approved, lgtm, size/XS

#114 Provide a way to disable DHCP in dnsmasq
  Dockerfile
  dnsmasq.conf.ipv4
  dnsmasq.conf.ipv6
  dnsmasq.conf.j2
  ironic-common.sh
  rundnsmasq.sh
Labels: approved, lgtm, size/L

#121 Remove outdated instruction related to log files
  README.md
Labels: approved, lgtm

#123 Fix bootloader copy
  runhttpd.sh
  runironic-conductor.sh
Labels: approved, lgtm, size/XS

#124 add HTTP port in bootloader configuration for ironic
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#125 Add python-sushy-oem-idrac pkg for vmedia boot interface
  Dockerfile
Labels: approved, lgtm, size/XS

#100 Start using Centos 8 as base
  Dockerfile
Labels: approved, lgtm, size/S

#127 Fix python version in rundnsmasq
  rundnsmasq.sh
Labels: approved, lgtm, size/XS

#128 Use Centos 8 as base for the builder
  Dockerfile
Labels: approved, lgtm, size/XS

#129 Add E2E build status in Readme
  README.md
Labels: approved, lgtm, size/S

#133 Add ironic automated_clean configuration option
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#131 export HTTP_PORT
  rundnsmasq.sh
Labels: approved, lgtm, size/XS
