Repository metal3-io/ironic-image, pull requests merged in 2020-12, with the labels that each got.

#227 Introduce separate ARG for extra packages list
  Dockerfile
  prepare-image.sh
Labels: approved, lgtm, size/S

#232 Fix incorrect IPA option (closes baremetal-operator#461)
  ironic.conf.j2
Labels: approved, lgtm, size/XS

#193 Add support for noop management and manual-management
  ironic.conf.j2
Labels: approved, lgtm, size/XS

#209 Provide a way to apply upstream patches to the image
  Dockerfile
  README.md
  patch-image.sh
  prepare-image.sh
Labels: approved, lgtm, size/M

#234 Enable ramdisk deploy_interface
  ironic.conf.j2
Labels: approved, lgtm, size/XS

#226 Allow setting sshkey and kernel params for debugging IPA
  Dockerfile
  README.md
  configure-ironic.sh
  inspector.ipxe
  inspector.ipxe.j2
  ironic-common.sh
  ironic.conf.j2
  runhttpd.sh
Labels: approved, lgtm, size/M

#235 Prevent unbound variable error in prepare-image
  prepare-image.sh
Labels: approved, lgtm, size/XS
