Repository metal3-io/ironic-image, pull requests merged in 2021-08, with the labels that each got.

#289 Rework runlogwatch.sh
  scripts/runlogwatch.sh
Labels: approved, lgtm, size/M

#290 Allow customize base image
  resources/vbmc/Dockerfile
Labels: size/XS, lgtm, approved

#291 Fix missing http port in iso url
  scripts/configure-ironic.sh
Labels: size/XS, lgtm, approved

#268 Switch to Centos 8 Stream base image
  Dockerfile
  prepare-image.sh
  resources/vbmc/Dockerfile
Labels: lgtm, approved, size/S

#293 Add procps package to make `ps` available
  main-packages-list.txt
Labels: size/XS, lgtm, approved

#294 [trivial] reorder packages list content
  main-packages-list.txt
Labels: size/XS, lgtm, approved

#292 Allow customize base image
  Dockerfile
Labels: size/XS, lgtm, approved

#295 Improve documentation about patching images
  README.md
Labels: lgtm, approved, size/M
