Repository metal3-io/ironic-image, pull requests merged in 2021-11, with the labels that each got.

#318 Update ipxe source to support IPV6 by default
  Dockerfile
Labels: size/XS, lgtm, approved

#320 Create EFI esp.img on aarch64
  Dockerfile
Labels: size/XS, lgtm, approved, ok-to-test

#321 Enable other git hosts than opendev for patch list
  README.md
  patch-image.sh
Labels: size/XS, lgtm, approved

#304 Add option to build image using source code directly
  Dockerfile
  README.md
  ironic-rpm-list.txt
  ironic-source-list.txt
  main-packages-list.txt
  prepare-image.sh
  scripts/configure-ironic.sh
Labels: lgtm, approved, size/M

#324 Follow-up to build image from source
  ironic-rpm-list.txt
  ironic-source-list.txt
  prepare-image.sh
Labels: lgtm, approved, size/S
