Repository metal3-io/ironic-image, pull requests merged in 2021-12, with the labels that each got.

#327 Move RUN commands to prepare-image
  Dockerfile
  prepare-image.sh
Labels: lgtm, approved, size/S

#323 Refactor patch-image script
  patch-image.sh
Labels: lgtm, approved, size/S

#331 Don't always pass ignition config in PXE kernel args
  scripts/coreos-ipa-common.sh
Labels: size/XS, lgtm, approved

#332 Do not remove pip in the source build
  prepare-image.sh
Labels: size/XS, lgtm, approved

#334 Move tftp_master_path to a subdirectory (fixes #333)
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#329 Clean up deprecated and unnecessary PXE configuration
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#328 Make Ironic generate a boot.ipxe
  Dockerfile
  ironic-config/dnsmasq.conf.j2
  ironic-config/dualboot.ipxe
  ironic-config/ironic.conf.j2
  scripts/configure-httpd-ipa.sh
  scripts/runhttpd
Labels: lgtm, approved, size/M

#335 Remove unnecessary flag of ipcalc
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved

#337 Use IPv6-friendly URLs for CoreOS
  scripts/coreos-ipa-common.sh
Labels: size/XS, lgtm, approved

#336 Disable the node history feature
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved
