Repository metal3-io/ironic-image, pull requests merged in 2021-01, with the labels that each got.

#233 Wait for expected number of drivers starting API
  runironic-api.sh
Labels: approved, lgtm, size/S

#202 Make searching for Provisioning IP robust
  ironic-common.sh
Labels: approved, lgtm, size/S

#192 Update CI status badge
  README.md
Labels: approved, lgtm, lifecycle/stale, size/XS

#219 Take advantage of multi files COPY to simplify Dockerfile
  Dockerfile
  config/dnsmasq.conf.j2
  config/dualboot.ipxe
  config/httpd-modules.conf
  config/httpd.conf
  config/inspector.ipxe.j2
  config/ironic.conf.j2
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-api
  scripts/runironic-conductor
  scripts/runironic-exporter
  scripts/runlogwatch.sh
  scripts/runmariadb
Labels: approved, lgtm, size/S

#237 Allow specify package versions
  main-packages-list.txt
  prepare-image.sh
Labels: approved, lgtm, size/XS
