Repository metal3-io/ironic-image, pull requests merged in 2021-05, with the labels that each got.

#253 Merge ironic and ironic-inspector repositories, single Dockerfile
  Dockerfile
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  ironic-scripts/runlogwatch.sh
  main-packages-list.txt
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
  scripts/runironic-api
  scripts/runironic-conductor
  scripts/runironic-exporter
  scripts/runironic-inspector
  scripts/runlogwatch.sh
  scripts/runmariadb
Labels: approved, lgtm, size/L

#259 Fix the issue that the OS is not a Stream version
  prepare-image.sh
  scripts/ironic-common.sh
  scripts/runmariadb
Labels: approved, lgtm, size/XS

#257 Increase ESP size
  Dockerfile
Labels: approved, lgtm, size/XS

#262 Add space before ']'
  scripts/runironic-inspector
Labels: approved, lgtm, size/XS

#247 Restart Ironic when certificate is updated
  prepare-image.sh
  scripts/configure-ironic.sh
  scripts/runhttpd
  scripts/runironic-api
  scripts/runironic-conductor
  scripts/runmariadb
Labels: approved, lgtm, size/M

#261 Add parameter to set boot iso source
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, size/XS

#260 Fix the "permisison denied" bug properly
  scripts/runmariadb
Labels: approved, lgtm, size/XS

#258 Set webserver_verify_ca to bool or certificate path
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, size/XS

#267 Add sushy-tools & vbmc Dockerfiles
  resources/sushy-tools/Dockerfile
  resources/vbmc/Dockerfile
Labels: approved, lgtm, size/S

#264 Keep only one httpd instance for the Ironic deployment
  prepare-image.sh
  scripts/runhttpd
  scripts/runironic-api
Labels: approved, lgtm, size/S

#270 OWNERS: Add Iury to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#271 Add options for external_http_url and external_callback_url
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: approved, lgtm, size/S
