Repository metal3-io/ironic-image, pull requests merged in 2021-09, with the labels that each got.

#297 Bug: Don't allow unauthenticated access to Ironic
  ironic-config/apache2-ironic-api.conf.j2
Labels: lgtm, approved, size/S

#298 Remove the trailing slash from the heartbeat rule
  ironic-config/apache2-ironic-api.conf.j2
Labels: size/XS, lgtm, approved

#299 Fix indentation issue
  ironic-config/apache2-ironic-api.conf.j2
Labels: lgtm, approved, size/S

#300 Bump sushy-tools to 0.18.0
  resources/sushy-tools/Dockerfile
Labels: lgtm, approved

#301 Update sushy-tools to 0.18.1 with an authentication fix
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#302 Remove outdated versions
  main-packages-list.txt
Labels: size/XS, lgtm, approved

#303 Refactor TLS params into a new helper script
  scripts/configure-ironic.sh
  scripts/runhttpd
  scripts/runironic-inspector
  scripts/tls-common.sh
Labels: lgtm, approved, size/L
