Repository metal3-io/ironic-image, pull requests merged in 2021-07, with the labels that each got.

#278 remove dhellmann from owners
  OWNERS
Labels: approved, lgtm, size/XS

#277 Update the inspector endpoint to port 5049 when using the reverse proxy
  prepare-image.sh
  scripts/runhttpd
  scripts/runironic-inspector
Labels: approved, lgtm, size/M

#282 Add namnx228 as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#279 Revert "Wait for expected number of drivers starting API"
  scripts/runironic-api
Labels: approved, lgtm, size/S

#281 Prevent installing docs via a DNF flag
  prepare-image.sh
Labels: approved, lgtm, size/XS

#280 [Trivial] Remove no-op require_agent_token
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, size/XS

#283 Remove workarounds for inspector merge
  scripts/runhttpd
  scripts/runironic-api
Labels: approved, lgtm, size/XS

#284 Enable missing vendor interfaces
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, size/XS

#285 Bump sushy-tools version
  resources/sushy-tools/Dockerfile
Labels: approved, lgtm, size/XS

#288 Update tripleo_repos location
  prepare-image.sh
  resources/vbmc/Dockerfile
Labels: approved, lgtm, size/XS

#286 Enable irmc bios interface
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, size/XS

#287 Add inspector callback_endpoint_override
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: approved, lgtm, size/XS
