Repository metal3-io/ironic-image, pull requests merged in 2021-03, with the labels that each got.

#230 Run ironic-api as WSGI when standalone with TLS capability
  Dockerfile
  config/apache2-ironic-api.conf.j2
  config/httpd-modules.conf
  config/ironic.conf.j2
  main-packages-list.txt
  prepare-image.sh
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runironic
  scripts/runironic-api
  scripts/runironic-conductor
Labels: approved, lgtm, size/L

#241 Prepare merging ironic and ironic-inspector repositories
  Dockerfile
  ironic-packages-list.txt
Labels: approved, lgtm, size/XS

#244 Support iLO4 and iLO5 BMCs
  config/ironic.conf.j2
  ironic-packages-list.txt
Labels: approved, lgtm, size/S

#246 Include vlan interfaces in introspection report
  config/inspector.ipxe.j2
  config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: approved, lgtm, size/S

#245 More preparation to merge ironic and inspector repos
  Dockerfile
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/dnsmasq.conf.j2
  ironic-config/dualboot.ipxe
  ironic-config/httpd-modules.conf
  ironic-config/httpd.conf
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic.conf.j2
  ironic-scripts/configure-httpd-ipa.sh
  ironic-scripts/configure-ironic.sh
  ironic-scripts/ironic-common.sh
  ironic-scripts/rundnsmasq
  ironic-scripts/runhttpd
  ironic-scripts/runironic-api
  ironic-scripts/runironic-conductor
  ironic-scripts/runironic-exporter
  ironic-scripts/runlogwatch.sh
  ironic-scripts/runmariadb
Labels: approved, lgtm, size/S

#249 Move ironic specific config to ironic Dockerfile
  Dockerfile
  prepare-image.sh
Labels: approved, lgtm, size/XS

#248 Remove net-tools installation
  ironic-scripts/runironic-api
  prepare-image.sh
Labels: approved, lgtm, size/XS
