Repository metal3-io/ironic-image, pull requests merged in 2022-03, with the labels that each got.

#358 Let Ironic handle retry instead of ipmitool
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#359 Add verbose logging to prepare-efi.sh
  prepare-efi.sh
Labels: size/XS, lgtm, approved

#356 Clean packages after install and added some env vars to sushy-tools container
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#326 Use centos stream 9 as base image
  Dockerfile
  main-packages-list.txt
  prepare-image.sh
Labels: lgtm, approved, size/S

#362 Fix missing semi-colon in runironic-inspector script
  scripts/runironic-inspector
Labels: size/XS, lgtm, approved

#360 Add option to choose TLS version
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/apache2-vmedia.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/tls-common.sh
Labels: size/XS, lgtm, approved

#363 🐛 Add python3-pip package to packages list to use pip3 in patch image script
  main-packages-list.txt
Labels: size/XS, lgtm, approved

#365 Drop unused ipxe.efi
  Dockerfile
  scripts/rundnsmasq
Labels: size/XS, lgtm, approved

#366 Increase power_state_change_timeout setting
  ironic-config/ironic.conf.j2
Labels: lgtm, approved
