Repository metal3-io/ironic-image, pull requests merged in 2022-01, with the labels that each got.

#340 Install the RPM of the combined Ironic
  ironic-rpm-list.txt
Labels: size/XS, lgtm, approved

#342 Set [irmc]kernel_append_params explicitly
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#339 Drop runmariadb in favor of mariadb-image
  README.md
  main-packages-list.txt
  scripts/runmariadb
Labels: lgtm, approved, size/M

#343 Add different variables for htpasswd of ironic and inspector
  ironic-config/apache2-ironic-api.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/configure-ironic.sh
  scripts/runhttpd
  scripts/runironic-inspector
Labels: lgtm, approved, size/M

#344 Fix authentication with Ironic reverse proxy
  ironic-config/apache2-ironic-api.conf.j2
Labels: lgtm, approved, size/S

#345 Move LISTEN_ALL_INTERFACES to ironic-common
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved

#347 Clean up reverse proxy support
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  scripts/ironic-common.sh
  scripts/runironic-inspector
Labels: lgtm, approved, size/S

#348 Fix authentication for inspector in reverse proxy mode
  ironic-inspector-config/inspector-apache.conf.j2
Labels: lgtm, approved, size/S

#349 move maelk to emeritus_reviewers list
  OWNERS
Labels: size/XS, lgtm, approved
