Repository metal3-io/ironic-image, pull requests merged in 2022-11, with the labels that each got.

#389 Add DNS or GW for use by dnsmasq
  README.md
  ironic-config/dnsmasq.conf.j2
  scripts/rundnsmasq
Labels: lgtm, approved, size/M

#387 Build vbmc on CentOS Stream 9
  resources/vbmc/Dockerfile
Labels: size/XS, lgtm, approved

#390 Allow customizing building from source
  Dockerfile
  README.md
  ironic-rpm-list
  ironic-source-list
  ironic-source-list.txt
  prepare-image.sh
Labels: lgtm, approved, size/M

#394 Add more DHCP options
  README.md
  ironic-config/dnsmasq.conf.j2
Labels: lgtm, approved, size/S

#396 Use local directory to build from source
  Dockerfile
  README.md
  ironic-source-list
  prepare-image.sh
  sources/.gitignore
Labels: lgtm, approved, size/M

#395 Correctly support IPv6 in DNS_IP and GATEWAY_IP
  ironic-config/dnsmasq.conf.j2
  scripts/rundnsmasq
Labels: size/XS, lgtm, approved

#370 Avoid unbound variables and other surprises in ironic-common
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
Labels: lgtm, approved, size/S

#397 Fix source build if building sushy from source
  prepare-image.sh
Labels: size/XS, lgtm, approved

#398 🐛 Fix centos httpd
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved

#400 Dockerfiles: use apt-get instead of apt
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#399 Add Lennart and Adam as reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#401 Remove RDO distribution configuration (finally fixes #46)
  prepare-image.sh
Labels: size/XS, lgtm, approved
