Repository metal3-io/ironic-image, pull requests merged in 2022-08, with the labels that each got.

#377 Update sushy-tools to version 0.20.0
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#372 Add option to to listen on a single inspector interface
  ironic-inspector-config/ironic-inspector.conf.j2
Labels: size/XS, lgtm, approved

#378 Support for unix sockets in reverse proxy mode
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  scripts/ironic-common.sh
  scripts/runironic-inspector
Labels: lgtm, approved, size/S

#379 Allow customizing public ports for Ironic and Inspector
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/ironic-python-agent.ign.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic-inspector
Labels: lgtm, approved, size/M

#380 Fix IRONIC_EXTERNAL_IP when TLS is used for virtual media
  scripts/configure-ironic.sh
Labels: size/XS, lgtm, approved

#381 Inspector: Set server name from variable
  ironic-inspector-config/inspector-apache.conf.j2
Labels: size/XS, lgtm, approved
