Repository metal3-io/ironic-image, pull requests merged in 2023-06, with the labels that each got.

#417 Default installation from source
  Dockerfile
  README.md
  prepare-image.sh
Labels: lgtm, approved, size/S

#415 Added IRONIC_IPA_COLLECTORS configuration option
  README.md
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
  scripts/runhttpd
Labels: lgtm, approved, ok-to-test, size/S

#418 Fixing patch-image.sh script for "$INSTALL_TYPE" == "source"
  patch-image.sh
Labels: size/XS, lgtm, approved

#416 Add customization, which are needed for multi-conductor scenario
  ironic-config/apache2-ironic-api.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/configure-ironic.sh
Labels: lgtm, approved, size/S

#423 Stop using extra-hardware by default
  README.md
  ironic-config/ironic-python-agent.ign.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  scripts/configure-ironic.sh
  scripts/runhttpd
Labels: lgtm, approved, size/S
