Repository metal3-io/ironic-image, pull requests merged in 2023-11, with the labels that each got.

#438 Support Firmware Interface
  ironic-config/ironic.conf.j2
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#442 Remove ServerName from httpd.conf
  ironic-config/httpd.conf.j2
Labels: size/XS, lgtm, approved

#433 Remove unused ironic-python-agent.ign.j2
  ironic-config/ironic-python-agent.ign.j2
Labels: lgtm, approved, size/M

#434 Add upper-constraints file customization
  Dockerfile
  README.md
  prepare-image.sh
  upper-constraints.txt
Labels: lgtm, approved, size/S

#446 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#445 Disable nova power notifications
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved, ok-to-test

#448 Allow guessing PROVISIONING_INTERFACE by PROVISIONING_IP
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved

#441 Consolidate the authentication code
  scripts/auth-common.sh
  scripts/configure-ironic.sh
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-inspector
Labels: lgtm, approved, size/L

#450 🌱 Add github action to trigger container image build
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/M

#449 Allow customizing conductor hostname
  README.md
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: size/XS, lgtm, approved

#453 Stop using the deprecated 'idrac' interface aliases
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved
