Repository metal3-io/ironic-image, pull requests merged in 2023-12, with the labels that each got.

#443 Minimum change to support inspection without inspector
  ironic-config/httpd-ironic-api.conf.j2
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic-inspector
Labels: lgtm, approved, size/M

#451 sushy-tools: make listen interface customizable
  resources/sushy-tools/Dockerfile
  resources/sushy-tools/redfish-emulator.sh
Labels: lgtm, approved, size/S

#458 Pin ironic and ironic-inspector for release-23.1
  Dockerfile
Labels: size/XS

#429 introduction of custom iPXE firmware support
  Dockerfile
  ironic-config/apache2-ipxe.conf.j2
  ironic-config/dnsmasq.conf.j2
  ironic-config/ipxe_config.template
  ironic-config/ironic.conf.j2
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
  scripts/tls-common.sh
Labels: lgtm, approved, size/L

#457 Add openstacksdk to sushy-tools container image
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved, ok-to-test

#460 add clomonitor badge to README
  README.md
Labels: size/XS, lgtm, approved

#463 add condition for ipxe_tls template usage
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#461 Update sushy-tools to 1.1.0
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved, ok-to-test

#464 Fix invalid iPXE TLS variables
  scripts/tls-common.sh
Labels: size/XS, lgtm, approved

#467 :seedling: add pull request template and workflow to verify it
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-verifier.yaml
Labels: lgtm, approved, size/S
