Repository metal3-io/ironic-image, pull requests merged in 2024-11, with the labels that each got.

#584 :bug: improve upper constraint handling
  Dockerfile
  prepare-image.sh
Labels: size/XS, lgtm, approved

#585 :warning: Remove rpm install method
  Dockerfile
  README.md
  ironic-packages-list
  ironic-rpm-list
  prepare-image.sh
Labels: lgtm, approved, size/L

#586 🌱 improve bash syntax in prepare-image
  prepare-image.sh
Labels: lgtm, approved, size/S

#588 🐛 improve upper constraints handling
  Dockerfile
  prepare-image.sh
Labels: size/XS, lgtm, approved

#590 🐛 improve upper constraints handling
  Dockerfile
  prepare-image.sh
Labels: size/XS, lgtm, approved

#587 :bug: improve upper constraints handling
  Dockerfile
  prepare-image.sh
Labels: size/XS, lgtm, approved, ok-to-test
