Repository metal3-io/ironic-image, pull requests merged in 2024-09, with the labels that each got.

#559 :bug: Pin ironic source
  ironic-source-list
Labels: size/XS, lgtm, approved

#560 🐛 Revert "pin ironic source"
  ironic-source-list
Labels: size/XS, lgtm, approved

#561 ✨ Enable redfish-https boot interface
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#548 🐛Fix CPU burning on ironic-log-watch when no ramdisk file is present
  scripts/runlogwatch.sh
Labels: lgtm, approved, ok-to-test, size/S

#563 🐛SQLite: fix Ironic container restarting issue
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved, ok-to-test

#568 :seedling: Reuse PR verifier wf from project-infra
  .github/workflows/pr-verifier.yaml
Labels: lgtm, approved, size/S

#569 :bug: Pin setuptools and pin upper-constraints
  prepare-image.sh
  upper-constraints.txt
Labels: lgtm, approved, size/XL

#572 :bug: Pin setuptools during image build
  prepare-image.sh
Labels: size/XS, lgtm, approved
