Repository metal3-io/ironic-image, pull requests merged in 2024-04, with the labels that each got.

#490 :seedling: Build virtualbmc image using python image
  resources/vbmc/Dockerfile
Labels: lgtm, approved, size/S

#492 ✨ Provide scripts to be used as liveness/readiness probes
  configure-nonroot.sh
  scripts/configure-ironic.sh
  scripts/ironic-probe.j2
Labels: lgtm, approved, size/M

#494 ⚠️ Use unix sockets by default for reverse proxy communication
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved

#482 🐛 Stop reading ironic and inspector HTPASSWD from environment variables
  scripts/auth-common.sh
Labels: lgtm, approved, size/S

#483 ⚠️ Completely remove support for ironic-inspector
  Dockerfile
  README.md
  configure-nonroot.sh
  docs/releasing.md
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  ironic-rpm-list
  ironic-source-list
  prepare-image.sh
  scripts/auth-common.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic-inspector
  scripts/runlogwatch.sh
  scripts/tls-common.sh
Labels: lgtm, approved, size/L

#498 🌱 Fix error in reading ironic htpasswd from file
  scripts/auth-common.sh
Labels: size/XS, lgtm, approved
