Repository metal3-io/ironic-image, pull requests merged in 2024-01, with the labels that each got.

#472 :bug: Ironic inspector iPXE address doesn't include brackets for IPv6 addresses
  ironic-config/inspector.ipxe.j2
Labels: size/XS, lgtm, approved

#473 🌱 Use bookworm slim to build sushy-tools image
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#456 🌱 Add tag trigger to images building wf
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/S

#471 🌱 reduce github actions permissions
  .github/workflows/build-images-action.yml
  .github/workflows/pr-verifier.yaml
Labels: lgtm, approved, size/M

#465 :book: add OpenSSF Scorecard badge to README
  README.md
Labels: size/XS, lgtm, approved

#469 🌱 Set require_managed_boot to False
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#474 :book: switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  hack/markdownlint.sh
Labels: lgtm, approved, size/S
