Repository metal3-io/ironic-image, pull requests merged in 2024-05, with the labels that each got.

#497 🌱 Update build status on release-23.1
  README.md
Labels: size/XS, lgtm, approved

#505 🌱 Add Slack notification for image build workflow failure
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/S

#509 🌱 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, size/M

#504 🐛 Disable unused network interfaces
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved, ok-to-test
