Repository metal3-io/ironic-image, pull requests merged in 2024-03, with the labels that each got.

#480 :bug: Fix vbmc container build after tripleo deprecation
  resources/vbmc/Dockerfile
Labels: lgtm, approved, size/S

#481 🌱 fix build images action in release-23.1
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/M

#479 ⚠️ Disable ironic-inspector by default
  ironic-config/ironic.conf.j2
  scripts/ironic-common.sh
Labels: lgtm, approved, size/S

#484 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/XS, lgtm, approved

#485 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/XS, lgtm, approved

#486 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/XS, lgtm, approved

#487 ⚠️ Remove support for API/conductor split
  ironic-config/httpd-ironic-api.conf.j2
  ironic-config/httpd-modules.conf
  ironic-config/ironic.conf.j2
  main-packages-list.txt
  scripts/auth-common.sh
  scripts/configure-ironic.sh
  scripts/runironic
  scripts/runironic-api
  scripts/runironic-conductor
Labels: lgtm, approved, size/L

#488 ⚠️ Remove ibmc and idrac drivers
  ironic-config/ironic.conf.j2
  ironic-rpm-list
  ironic-source-list
Labels: lgtm, approved, size/S

#491 🌱 add ARG BASE_IMAGE to sushy-tools Dockerfile
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved
