Repository metal3-io/ironic-image, pull requests merged in 2024-08, with the labels that each got.

#536 :seedling: Disable pip cache
  prepare-image.sh
Labels: size/XS, lgtm, approved

#537 :seedling: Move Image build to GH runner
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/M

#539 🌱 Fix syntax in build images github workflow
  .github/workflows/build-images-action.yml
Labels: size/XS, lgtm, approved

#535 :sparkles: Enable FIPS mode for IPA if system is in FIPS mode
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: lgtm, approved, size/S

#545 🌱 Bump default sushy-tools version to 1.3.0
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#546 🌱 Update for release-26.0
  Dockerfile
  upper-constraints.txt
Labels: lgtm, approved, size/XL
