Repository metal3-io/ironic-image, pull requests merged in 2025-06, with the labels that each got.

#692 :sparkles: add new release automation and documentation
  .github/workflows/release.yaml
  Makefile
  docs/releasing.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/release/notes.go
  releasenotes/.gitkeep
Labels: lgtm, approved, size/XL

#699 :bug: fix release image building
  .github/workflows/release.yaml
  docs/releasing.md
Labels: lgtm, approved, size/M

#701 📖 Update DHCP_RANGE description
  README.md
Labels: size/XS, lgtm, approved
