Repository metal3-io/ironic-image, pull requests merged in 2025-01, with the labels that each got.

#607 :seedling: Use pynotify instead of inotify-tools
  main-packages-list.txt
  prepare-image.sh
  scripts/runhttpd
  scripts/runironic
  scripts/runlogwatch.sh
Labels: lgtm, approved, size/M

#608 :warning: Remove ironic-lib dependency
  Dockerfile
  README.md
  docs/releasing.md
  ironic-packages-list
  prepare-image.sh
Labels: lgtm, approved, size/S

#610 🐛 Install python-ironicclient in /usr/local
  resources/ironic-client/Dockerfile
Labels: size/XS, lgtm, approved

#612 🐛 Drop quiet option of grep to avoid race condition with pipefail
  scripts/ironic-common.sh
Labels: size/XS, lgtm, approved, ok-to-test
