Repository metal3-io/ironic-image, pull requests merged in 2025-07, with the labels that each got.

#709 ✨ Support DEPLOY_KERNEL_URL and DEPLOY_RAMDISK_URL
  README.md
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: lgtm, approved, size/S

#712 🐛 Remove extra slash from deploy kernel/ramdisk paths
  scripts/configure-ironic.sh
Labels: size/XS, lgtm, approved

#708 :bug: Fix dnsmasq config ipv6 issues
  ironic-config/dnsmasq.conf.j2
Labels: lgtm, approved, size/M

#711 🌱 Clarify supported branches
  docs/releasing.md
Labels: lgtm, approved, size/S
