Repository metal3-io/ironic-image, pull requests merged in 2025-09, with the labels that each got.

#751 :seedling: add edited as irso functional trigger
  .github/workflows/irso-functional.yml
Labels: lgtm, approved

#722 :seedling: use new cncf oracle gh runners
  .github/workflows/irso-functional.yml
Labels: size/XS, lgtm, approved

#757 :seedling: Revert "Use the shared directory to store master iso images on ironic-conductor node"
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#760 :seedling: Pin constraints, prepare release-32.0
  Dockerfile
  upper-constraints.txt
Labels: lgtm, approved, size/XL

#761 :rocket: Release v32.0.0
  releasenotes/v32.0.0.md
Labels: lgtm, approved, size/M
