Repository metal3-io/ironic-image, pull requests merged in 2025-03, with the labels that each got.

#636 :bug: remove faulty NUMPROC logic
  scripts/configure-ironic.sh
Labels: size/XS, lgtm, approved

#637 ⚠️ Deprecate passing MARIADB_PASSWORD in favour of mounting a secret
  README.md
  scripts/auth-common.sh
  scripts/configure-ironic.sh
Labels: lgtm, approved, size/M

#581 :sparkles: Install shim-pkg explicitly and add support for CentOS Stream 10
  README.md
  prepare-efi.sh
Labels: size/XS, lgtm, approved

#642 ⚠️ Set IRONIC_USE_MARIADB to false by default in all cases
  README.md
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runironic
Labels: lgtm, approved, size/M

#643 🌱 Refactoring: add a helper for restarting a service on certificate update
  scripts/runhttpd
  scripts/runironic
  scripts/tls-common.sh
Labels: lgtm, approved, size/M

#623 ✨ Add scripts to run database upgrades and online migrations
  scripts/rundatabase-upgrade
  scripts/runironic
  scripts/runonline-data-migrations
Labels: lgtm, approved, size/S

#647 🌱 Update sushy-tools to 2.0.0
  resources/sushy-tools/Dockerfile
Labels: size/XS, lgtm, approved

#628 🐛 Allow override of `http_url`, etc for different network topologies
  ironic-config/dnsmasq.conf.j2
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
Labels: lgtm, approved, size/M, ok-to-test

#649 :seedling: Update virtualbmc version to 3.2.0
  resources/vbmc/Dockerfile
Labels: size/XS, lgtm, approved

#646 :sparkles: Add build ironic-image with CentOS Stream 10
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/S

#651 :bug: Revert "Add build ironic-image with CentOS Stream 10"
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/S

#653 :bug: harmonize custom config/data paths and db data migration
  ironic-config/ironic.conf.j2
  scripts/ironic-common.sh
  scripts/rundatabase-upgrade
  scripts/runhttpd
  scripts/runonline-data-migrations
Labels: lgtm, approved, size/S

#654 :sparkles: Add build ironic-image with CS10, take two
  .github/workflows/build-images-action.yml
Labels: lgtm, approved, size/S

#655 :seedling: Configure release-29.0
  Dockerfile
  upper-constraints.txt
Labels: lgtm, approved, size/XL
