Repository metal3-io/ironic-image, pull requests merged in 2025-05, with the labels that each got.

#674 :bug: Use local upper-constraints
  upper-constraints.txt
Labels: lgtm, approved, size/XL

#677 🌱 Add a helper script to parse ramdisk logs
  tools/parse-ramdisk-logs.py
Labels: lgtm, approved, size/L

#681 🐛 OSSA-2025-001: set file_url_allowed_paths to what Metal3 uses
  ironic-config/ironic.conf.j2
Labels: size/XS, lgtm, approved

#676 :warning: Use Python 3.12 to build and run ironic
  main-packages-list.txt
  prepare-image.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runlogwatch.sh
  scripts/tls-common.sh
  upper-constraints.txt
Labels: lgtm, approved, size/XL

#683 🌱 Minor improvements for tools/parse-ramdisk-logs.py
  tools/parse-ramdisk-logs.py
Labels: lgtm, approved, size/L

#684 :seedling: Install jinja2 and pyinotify constrained
  prepare-image.sh
Labels: lgtm, approved, size/S

#686 :warning: Do not install separate sushy-oem-idrac
  ironic-packages-list
Labels: size/XS, lgtm, approved

#685 :warning: Use Python 3.12 for resources images
  resources/ironic-client/Dockerfile
  resources/sushy-tools/Dockerfile
  resources/vbmc/Dockerfile
Labels: size/XS, lgtm, approved
