Repository metal3-io/ironic-image, pull requests merged in 2025-08, with the labels that each got.

#721 :seedling: Pin constraints, prepare release-31.0
  Dockerfile
  upper-constraints.txt
Labels: lgtm, approved, size/XL

#723 :bug: Revert "Fix dnsmasq config ipv6 issues"
  ironic-config/dnsmasq.conf.j2
Labels: lgtm, approved, size/M

#726 :rocket: Release v31.0.0
  releasenotes/v31.0.0.md
Labels: lgtm, approved, size/M

#703 :book: update docs/releasing.md on dependabot configs
  docs/releasing.md
Labels: lgtm, approved, size/S

#733 🌱 Approvers: remove Derek, add Adam
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#732 🐛 Disable unused httpd mod_proxy extensions
  ironic-config/httpd-modules.conf
Labels: size/XS, lgtm, approved

#730 :warning: Use watchdog to monitor logs and certificate changes
  prepare-image.sh
  scripts/runlogwatch.sh
  scripts/tls-common.sh
Labels: lgtm, approved, size/M

#734 :bug: Fix CentOS Stream 10 build
  prepare-efi.sh
Labels: size/XS, lgtm, approved
