Repository metal3-io/ironic-image, pull requests merged in 2025-04, with the labels that each got.

#661 🐛 Stop doing mkdir on /certs subdirectories
  scripts/tls-common.sh
Labels: size/XS, lgtm, approved

#660 :seedling: do not bump major version of github actions
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#663 🌱 Synchronize the IrSO functional job with IrSO
  .github/workflows/irso-functional.yml
  hack/ci-e2e.sh
Labels: lgtm, approved, size/M

#664 🐛 Do not use /tmp as a source directory for the image
  Dockerfile
  README.md
  ironic-config/httpd.conf.j2
  ironic-config/ironic.conf.j2
  scripts/rundnsmasq
  scripts/runhttpd
Labels: lgtm, approved, size/M

#666 :seedling: add labels to dockerfile
  Dockerfile
Labels: lgtm, approved, size/S

#667 :seedling: add labels to Dockerfiles in resources
  resources/ironic-client/Dockerfile
  resources/sushy-tools/Dockerfile
  resources/vbmc/Dockerfile
Labels: lgtm, approved, size/S

#616 🌱 Enables sushy-tool image multiarch builds
  .github/workflows/build-images-action.yml
  README.md
Labels: size/XS, lgtm, approved, ok-to-test

#670 🌱 Use a multi-node cluster in functional tests
  .github/workflows/irso-functional.yml
  hack/ci-e2e.sh
Labels: lgtm, approved, size/S

#669 🌱 Use bootloader through a local file link
  ironic-config/ironic.conf.j2
  scripts/runhttpd
Labels: size/XS, lgtm, approved

#652 📖 Expand docs on ramdisk ssh key
  README.md
Labels: size/XS, lgtm, approved

#673 🐛 Extract files one-by-one in logwatch
  scripts/runlogwatch.sh
Labels: size/XS, lgtm, approved
