Repository metal3-io/ironic-image, pull requests merged in 2025-02, with the labels that each got.

#619 📖 Releasing: add IrSO to post-release actions
  docs/releasing.md
Labels: lgtm, approved, size/S

#618 :bug: Fix runlogwatch failure if LOG_DIR does not exist
  scripts/runlogwatch.sh
Labels: size/XS, lgtm, approved

#620 🌱 Run the IrSO functional job on ironic-images changes
  .github/workflows/irso-functional.yml
  hack/ci-e2e.sh
Labels: lgtm, approved, size/M

#621 :seedling: add dependabot configuration for actions
  .github/dependabot.yml
Labels: lgtm, approved, size/S

#518 ✨ Allow independent credentials for JSON RPC
  scripts/auth-common.sh
  scripts/configure-ironic.sh
Labels: lgtm, approved, size/M

#624 :seedling: Add change to supported versions in release docs
  docs/releasing.md
Labels: lgtm, approved, size/S

#626 :seedling: trivial: fix typo in releasing docs
  docs/releasing.md
Labels: size/XS, lgtm, approved

#629 :seedling: Configure release-28.0
  Dockerfile
  upper-constraints.txt
Labels: lgtm, approved, size/XL

#631 :bug: Fix runlogwatch script
  scripts/runlogwatch.sh
Labels: lgtm, approved, size/S
